'use strict';
const root=document.getElementById('app');
const terms=[
{id:'kutikula',name:'Kutikula',description:'Eine dünne, wachsartige Schutzschicht ganz außen auf dem Blatt. Sie vermindert den Wasserverlust.',x:37.2,y:15.8},
{id:'oben',name:'Obere Epidermis',description:'Eine dicht geschlossene Zellschicht an der Blattoberseite. Sie liegt direkt unter der Kutikula und schützt das Blatt.',x:29,y:19},
{id:'palisade',name:'Palisadengewebe',description:'Längliche Zellen stehen dicht nebeneinander unter der oberen Epidermis. Sie enthalten besonders viele Chloroplasten.',x:37,y:32},
{id:'schwamm',name:'Schwammgewebe',description:'Locker angeordnete, unregelmäßige Zellen mit großen Hohlräumen dazwischen. Durch diese Hohlräume können sich Gase im Blatt verteilen.',x:33,y:53},
{id:'ader',name:'Blattader',description:'Ein Bündel von Transportbahnen im Blattinneren. Größere Gefäße leiten Wasser; Siebröhren transportieren Zucker weiter.',x:66.7,y:56},
{id:'unten',name:'Untere Epidermis',description:'Eine dicht geschlossene Zellschicht an der Blattunterseite. In ihr liegen beim dargestellten Blatt die Spaltöffnungen.',x:78,y:77.5},
{id:'spalt',name:'Spaltöffnung',description:'Eine kleine Lücke zwischen zwei Schließzellen, hier an der Blattunterseite. Sie verbindet die Hohlräume im Blatt mit der Außenluft.',x:57.3,y:86}];
const chloroplast={id:'chloroplasten',name:'Chloroplasten'};
const state={selected:null,assigned:{},assignmentChecked:false,questions:{},questionsChecked:false,cloze:{},clozeChecked:false};
const order=['entdecken','elektronen','licht','zuordnen','fragen','lueckentext','abschluss'];
const labels=['Das Blatt','Elektronenmikroskop','Lichtmikroskop','Zuordnen','Nachdenken','Lückentext','Abschluss'];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const byId=id=>terms.find(t=>t.id===id);
function navigate(route){location.hash=route;}
function steps(route){return '<nav class="steps" aria-label="Lernschritte">'+order.map((s,i)=>'<a class="step" href="#'+s+'" '+(s===route?'aria-current="step"':'')+'>'+(i+1)+' · '+labels[i]+'</a>').join('')+'</nav>';}
function heading(kicker,title,intro=''){return '<span class="eyebrow">'+kicker+'</span><h1 tabindex="-1">'+title+'</h1>'+(intro?'<p class="intro">'+intro+'</p>':'');}
function actions(previous,next,nextLabel='Weiter'){return '<div class="actions"><a class="button secondary" href="#'+previous+'">← Zurück</a>'+(next?'<a class="button" href="#'+next+'">'+nextLabel+' →</a>':'')+'</div>';}
function home(){return heading("Naturwissenschaften · Dein Lernprogramm","Ökosystem Wald","Wähle deinen Bereich.")+"<div class=\"tiles\"><a class=\"tile\" href=\"#unterricht\"><img src=\"assets/unterricht-cover.png\" alt=\"Artenreicher Wald mit Pflanzen, Tieren, Pilzen, Bodenorganismen und einem Bach\"><div class=\"tile-body\"><h2>Unterrichtsinhalte</h2><p>Hier bearbeitest du die Themen aus dem Unterricht.</p><div class=\"tile-bottom\"><span>2 Lernprogramme</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a><a class=\"tile\" href=\"#zusatz\"><img src=\"assets/baum.png\" alt=\"Laubbaum mit Wurzeln, Stamm und Krone\"><div class=\"tile-body\"><h2>Zusatzaufgaben</h2><p>Hier findest du weitere Aufgaben zum selbstständigen Arbeiten.</p><div class=\"tile-bottom\"><span>Baum und Laubblatt</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a></div>";}
function unterrichtHome(){return heading("Naturwissenschaften · Dein Lernprogramm","Unterrichtsinhalte","Wähle ein Thema aus dem Unterricht.")+"<div class=\"tiles\"><a class=\"tile food-tile\" href=\"#nahrung-start\"><img src=\"assets/M1_08_Rotfuchs.png\" alt=\"Organismenkarte Rotfuchs im Wald\"><div class=\"tile-body\"><span class=\"tag\">Nahrungsbeziehungen untersuchen</span><h2>Wer frisst wen?</h2><p>Baue mit acht Organismenkarten ein Nahrungsnetz und fülle dabei dein Arbeitsblatt aus.</p><div class=\"tile-bottom\"><span>Verbinden · Auswerten · Folgen erklären</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a><a class=\"tile\" href=\"wald-funktionsfaehig/index.html\"><img src=\"wald-funktionsfaehig/assets/waldsystem-start.png\" alt=\"Artenreicher Wald mit Pflanzen, Tieren, Bodenorganismen und Sonnenlicht\"><div class=\"tile-body\"><span class=\"tag\">Stoffkreislauf · Nischen · Waldnutzung</span><h2>Wie bleibt der Wald funktionsfähig?</h2><p>Bearbeite die beiden Pflichtarbeitsblätter und untersuche, wie Stoffe, Lebewesen und menschliche Eingriffe zusammenwirken.</p><div class=\"tile-bottom\"><span>Erarbeiten · Übertragen · Beurteilen</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a></div>"+actions('start');}
function zusatzHome(){return heading("Naturwissenschaften · Dein Lernprogramm","Zusatzaufgaben","Wähle eine Zusatzaufgabe und lege das passende Arbeitsblatt bereit.")+"<div class=\"tiles\"><a class=\"tile\" href=\"#baum\"><img src=\"assets/baum.png\" alt=\"Laubbaum mit Krone, Stamm und Wurzeln\"><div class=\"tile-body\"><span class=\"tag\">Pflanzenorgane verstehen</span><h2>Wurzel, Stamm und Krone</h2><p>Erkunde den Bau eines Baumes und die Aufgaben seiner Teile.</p><div class=\"tile-bottom\"><span>Entdecken · Zuordnen · Wurzellupe</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a><a class=\"tile\" href=\"#entdecken\"><img src=\"assets/laubblatt.png\" alt=\"Grünes Laubblatt mit sichtbaren Blattadern\"><div class=\"tile-body\"><span class=\"tag\">Blätter verstehen</span><h2>Der Aufbau eines Laubblattes</h2><p>Vom ganzen Blatt bis zu seinen kleinsten Bausteinen.</p><div class=\"tile-bottom\"><span>Entdecken · Zuordnen · Üben</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a><a class=\"tile\" href=\"#sonnenblatt\"><img src=\"assets/sonne-schatten-blaetter.png\" alt=\"Sonnenblatt und Schattenblatt im Vergleich\"><div class=\"tile-body\"><span class=\"tag\">Vertiefung · Blattaufbau</span><h2>Sonnenblatt und Schattenblatt</h2><p>Vergleiche Blattfläche und Gewebe bei unterschiedlichen Lichtverhältnissen.</p><p class=\"subtle\"><strong>Zuerst bearbeiten:</strong> Der Aufbau eines Laubblattes</p><div class=\"tile-bottom\"><span>Vergleichen · Erklären · Anwenden</span><span class=\"round\" aria-hidden=\"true\">→</span></div></div></a></div>"+actions('start');}
function entry(){return heading('01 · Genau hinschauen','Ein Blatt. Viele Bausteine.','Von außen wirkt ein Laubblatt dünn und einfach. Was verbirgt sich in seinem Inneren?')+'<div class="lead-grid"><div class="leaf-stage"><img src="assets/laubblatt.png" alt="Ein grünes Laubblatt mit verzweigten Blattadern"><button class="magnifier" data-go="elektronen" aria-label="Mit der Lupe in das Blatt hineinsehen"><svg viewBox="0 0 48 48" fill="none" aria-hidden="true"><circle cx="20" cy="20" r="12" stroke="currentColor" stroke-width="4"/><path d="M29 29L42 42" stroke="currentColor" stroke-width="5" stroke-linecap="round"/><path d="M14 20h12M20 14v12" stroke="currentColor" stroke-width="3"/></svg></button></div><section class="panel"><h2>Schau ins Blatt hinein</h2><p>Klicke auf die Lupe. Du siehst dann einen stark vergrößerten <strong>Querschnitt</strong>: Stell dir vor, das Blatt wird quer durchgeschnitten und du schaust auf die Schnittkante.</p><div class="note"><strong>Arbeitsblatt bereit?</strong><br>Du wirst die Schichten kennenlernen und anschließend dein Blatt beschriften.</div></section></div>'+actions('zusatz');}
function microscopy(kind){
const sem=kind==='elektronen';
return heading(sem?'02 · Elektronenmikroskop':'03 · Lichtmikroskop',sem?'Eine Landschaft aus Zellen':'Die grünen Bausteine werden sichtbar')+
'<div class="lead-grid"><figure class="panel image-panel" style="margin:0"><img class="micro-image" src="assets/'+(sem?'elektronenmikroskop':'lichtmikroskop')+'.png" alt="'+(sem?'Räumlich wirkender Blattquerschnitt mit länglichen Zellen oben und großen Hohlräumen darunter':'Heller Blattquerschnitt mit vielen kleinen grünen Chloroplasten in den Zellen')+'"><figcaption class="caption">KI-generierte Darstellung nach dem Vorbild '+(sem?'einer kolorierten Rasterelektronenmikroskopaufnahme':'einer lichtmikroskopischen Aufnahme')+'. Keine echte Mikroskopaufnahme.</figcaption></figure><section>'+
(sem?'<h2>Sehr stark vergrößert</h2><p>Ein <strong>Rasterelektronenmikroskop</strong> tastet eine vorbereitete Probe mit einem Elektronenstrahl ab. So werden feine Oberflächen und Zellwände sichtbar. Das Bild wirkt räumlich.</p><p>Die kleinen rundlichen Körper in den aufgeschnittenen Zellen stellen <strong>Chloroplasten</strong> dar. In einem echten Blatt enthalten sie den grünen Farbstoff <strong>Chlorophyll</strong>. Er sorgt für die grüne Blattfarbe und nimmt Licht für die Fotosynthese auf.</p><div class="note"><strong>Grün durch Nachfärben:</strong> Elektronenmikroskopische Aufnahmen sind zunächst schwarz-weiß. Die Grüntöne werden nachträglich hinzugefügt – sie zeigen hier nicht die natürliche Farbe.</div>':
'<h2>Licht statt Elektronen</h2><p>Ein <strong>Lichtmikroskop</strong> vergrößert mit sichtbarem Licht und Linsen. Bei einem dünnen Blattschnitt kann Licht durch das Gewebe hindurchfallen.</p><p>Deshalb wirkt die Darstellung heller, durchscheinender und flacher als das räumliche Bild des Elektronenmikroskops. Die kleinen grünen <strong>Chloroplasten</strong> lassen sich hier besonders gut von den übrigen Zellbestandteilen unterscheiden.</p><div class="note"><strong>Schau genau hin:</strong> In welchen Zellen entdeckst du besonders viele Chloroplasten? Merke dir ihre Form und Lage für die nächste Aufgabe.</div>')+
'</section></div>'+actions(sem?'entdecken':'elektronen',sem?'licht':'zuordnen',sem?'Weiter':'Zur Zuordnung');
}
function assign(slot,id){if(!Number.isInteger(slot)||slot<0||slot>=terms.length||!byId(id))throw Error('Ungültige Zuordnung');for(const key of Object.keys(state.assigned))if(state.assigned[key]===id)delete state.assigned[key];state.assigned[slot]=id;state.assignmentChecked=false;}
function assignmentPage(){const current=byId(state.selected);const correct=terms.filter((t,i)=>state.assigned[i]===t.id).length;
return heading('04 · Begriffe zuordnen','Welche Schicht ist welche?','1. Klicke auf einen Begriff und lies den Hinweis. 2. Klicke auf die passende Stelle im Bild oder in der Liste darunter.')+
'<div class="task-layout"><section><div class="diagram"><img src="assets/schema.png" alt="Unbeschriftetes Schema des Blattquerschnitts. Sieben markierte Stellen können mit Begriffen belegt werden."><svg aria-hidden="true" viewBox="0 0 1536 1024" style="position:absolute;inset:0;width:100%;height:100%;pointer-events:none"><path d="M880 860V805" stroke="#163d30" stroke-width="3"/></svg>'+
terms.map((t,i)=>{const a=state.assigned[i];return '<button class="spot '+(a?'filled ':'')+(state.assignmentChecked?(a===t.id?'correct':'wrong'):'')+'" style="left:'+t.x+'%;top:'+t.y+'%" data-slot="'+i+'" aria-label="Stelle '+(i+1)+(a?': '+byId(a).name:': noch frei')+'" title="'+(a?byId(a).name:'Stelle '+(i+1))+'">'+(i+1)+'</button>';}).join('')+
'</div><div class="assignment-list">'+terms.map((t,i)=>'<button class="assignment" data-slot="'+i+'"><strong>'+(i+1)+'</strong> · '+(state.assigned[i]?esc(byId(state.assigned[i]).name):'Noch frei')+(state.assignmentChecked?' '+(state.assigned[i]===t.id?'✓':'– prüfen'):'')+'</button>').join('')+'</div></section><aside class="panel"><h2>Deine Begriffe</h2><div class="terms">'+[terms[3],terms[0],terms[6],terms[2],terms[5],terms[4],terms[1]].map(t=>'<button class="term '+(Object.values(state.assigned).includes(t.id)?'used':'')+'" data-term="'+t.id+'" aria-pressed="'+(state.selected===t.id)+'">'+t.name+'</button>').join('')+'</div><div class="description" aria-live="polite">'+(current?'<h3>'+current.name+'</h3><p>'+current.description+'</p>':'<h3>Ein Hinweis für dich</h3><p>Wähle einen Begriff. Hier erfährst du, woran du die passende Struktur erkennst.</p>')+'</div><p class="subtle" style="margin-top:15px">Ändern: Wähle einen Begriff und setze ihn neu. Jede Bezeichnung gehört an genau eine Stelle.</p><button class="button" data-check="assignment">Zuordnung prüfen</button><div class="feedback" role="status">'+(state.assignmentChecked?(correct===7?'<span class="ok">✓ Alle 7 Begriffe stimmen!</span>':'<span class="bad">'+correct+' von 7 stimmen. Prüfe die markierten Stellen und lies die Hinweise noch einmal.</span>'):'')+'</div></aside></div><div class="note"><strong>Jetzt auf dein Arbeitsblatt:</strong> Übertrage nach dem Prüfen die sieben Begriffe zur passenden Nummer.</div>'+actions('licht','fragen');}
const questions=[
{q:'In welchem Gewebe befinden sich besonders viele Chloroplasten?',answer:'palisade',explanation:'Die dicht stehenden, länglichen Palisadenzellen enthalten besonders viele Chloroplasten.'},
{q:'Welche Schicht vermindert das Austrocknen des Blattes?',answer:'kutikula',explanation:'Die wachsartige Kutikula bremst den Wasserverlust über die Blattoberfläche.'},
{q:'Durch welche Öffnung werden Gase und Wasserdampf mit der Umgebung ausgetauscht?',answer:'spalt',explanation:'Die Spaltöffnung verbindet die Hohlräume im Blatt mit der Außenluft.'},
{q:'Welche Struktur enthält die Gefäße, die Wasser ins Blatt bringen?',answer:'ader',explanation:'Die Blattader enthält Gefäße für den Wassertransport und Siebröhren für den Zuckertransport.'}
];
function options(selected,items=terms){return '<option value="">Bitte wählen …</option>'+[...items].sort((a,b)=>a.name.localeCompare(b.name,'de')).map(t=>'<option value="'+t.id+'" '+(selected===t.id?'selected':'')+'>'+t.name+'</option>').join('');}
function questionPage(){const score=questions.filter((q,i)=>state.questions[i]===q.answer).length;
return heading('05 · Zusammenhänge verstehen','Was leisten die Teile des Blattes?','Wähle zu jeder Frage die passende Antwort. Wenn du unsicher bist, kannst du zur Zuordnung zurückgehen.')+
'<div class="question-grid">'+questions.map((q,i)=>'<section class="panel question"><label for="q'+i+'">'+(i+1)+'. '+q.q+'</label><select id="q'+i+'" data-question="'+i+'" class="'+(state.questionsChecked?(state.questions[i]===q.answer?'correct':'wrong'):'')+'">'+options(state.questions[i])+'</select><p class="answer-note" id="q-feedback-'+i+'">'+(state.questionsChecked?(state.questions[i]===q.answer?'✓ Richtig. '+q.explanation:'Noch nicht richtig. Denke an die Funktion der gesuchten Struktur.'):'')+'</p></section>').join('')+'</div><div class="actions"><button class="button" data-check="questions">Antworten prüfen</button><span class="feedback" role="status">'+(state.questionsChecked?score+' von 4 Antworten richtig.':'')+'</span></div>'+
actions('zuordnen','lueckentext');
}
const clozeAnswers=['kutikula','oben','palisade','chloroplasten','schwamm','ader','unten','spalt'];
function gap(i){return '<select aria-label="Lücke '+(i+1)+'" data-gap="'+i+'" class="'+(state.clozeChecked?(state.cloze[i]===clozeAnswers[i]?'correct':'wrong'):'')+'">'+options(state.cloze[i],[...terms,chloroplast])+'</select>'+(state.clozeChecked?'<span class="'+(state.cloze[i]===clozeAnswers[i]?'ok':'bad')+'" aria-label="'+(state.cloze[i]===clozeAnswers[i]?'richtig':'noch nicht richtig')+'">'+(state.cloze[i]===clozeAnswers[i]?'✓':'✕')+'</span>':'');}
function clozePage(){const score=clozeAnswers.filter((a,i)=>state.cloze[i]===a).length;
return heading('06 · Wissen festigen','Ein Blatt arbeitet im Team','Vervollständige den Text. Jeder der acht Begriffe passt genau einmal. Lies am Ende noch einmal den ganzen Text.')+
'<section class="panel cloze"><p>Ein Blatt soll Licht aufnehmen und dabei möglichst wenig Wasser verlieren. Seine äußere Wachsschicht, die '+gap(0)+', hilft dabei. Direkt darunter bildet an der Oberseite die '+gap(1)+' eine schützende Grenze.</p><p>Das einfallende Licht erreicht anschließend das '+gap(2)+'. In dessen Zellen liegen besonders viele '+gap(3)+'. Sie enthalten Chlorophyll und sind die Orte der Fotosynthese.</p><p>Weiter innen lässt das '+gap(4)+' viel Platz für die Verteilung von Gasen. Für den Transport von Wasser und Zucker ist die '+gap(5)+' wichtig.</p><p>An der Blattunterseite schließt die '+gap(6)+' das Gewebe nach außen ab. Eine regulierbare Verbindung zur Umgebung ist die '+gap(7)+'. Hier kann Kohlenstoffdioxid hinein- und Wasserdampf hinausgelangen.</p><button class="button" data-check="cloze">Lückentext prüfen</button><div class="feedback" role="status">'+(state.clozeChecked?(score===8?'✓ Alle 8 Lücken sind richtig!':score+' von 8 Lücken stimmen. Überarbeite die markierten Lücken.'):'')+'</div></section>'+
(state.clozeChecked&&score===8?'<section class="completion"><h2>Geschafft – du kennst den Blattaufbau!</h2><p>Prüfe zum Abschluss dein Arbeitsblatt: Sind alle sieben Strukturen beschriftet? Kannst du erklären, wozu die Chloroplasten da sind?</p></section>':'<div class="note"><strong>Arbeitsblatt-Check:</strong> Ergänze die Funktionen und halte fest, welche Aufgabe Chloroplasten übernehmen.</div>')+actions('fragen','abschluss','Zum Abschluss');}
function closingPage(){
const cards=[
['Das ganze Blatt','Von außen betrachtet','Die Blattfläche und ihre verzweigten Adern kannst du schon mit bloßem Auge erkennen.','laubblatt','Grünes Laubblatt mit sichtbaren Blattadern',''],
['Elektronenmikroskop','Zellwände und Hohlräume','Die räumliche Darstellung zeigt, wie die Zellen angeordnet sind und wo sich Hohlräume befinden.','elektronenmikroskop','Räumlich dargestellter Blattquerschnitt','KI-generierte Darstellung nach dem Vorbild einer kolorierten Rasterelektronenmikroskopaufnahme. Die Grüntöne sind nachträglich hinzugefügt; keine echte Mikroskopaufnahme.'],
['Lichtmikroskop','Chloroplasten in den Zellen','In der hellen, durchscheinenden Darstellung heben sich die kleinen grünen Chloroplasten gut ab.','lichtmikroskop','Blattquerschnitt mit deutlich erkennbaren Chloroplasten','KI-generierte Darstellung nach dem Vorbild einer lichtmikroskopischen Aufnahme; keine echte Mikroskopaufnahme.'],
['Schema','Der Aufbau auf einen Blick','Das vereinfachte Bild hilft dir, die Schichten und Strukturen des Blattes klar zu unterscheiden.','schema','Unbeschriftetes Schema des Blattquerschnitts','']];
return heading('07 · Zum Abschluss','Ein Blatt – vier Blickwinkel','Vom ganzen Blatt bis zum vereinfachten Querschnitt: Jede Darstellung macht etwas anderes sichtbar.')+
'<div class="closing-gallery">'+cards.map((c,i)=>'<figure class="panel"><figcaption><span class="eyebrow">0'+(i+1)+' · '+c[0]+'</span><h2>'+c[1]+'</h2><p>'+c[2]+'</p></figcaption><div class="'+(i===0?'leaf-stage':'')+'"><img class="micro-image" loading="lazy" src="assets/'+c[3]+'.png" alt="'+c[4]+'">'+'</div>'+(c[5]?'<p class="caption">'+c[5]+'</p>':'')+'</figure>').join('')+'</div>'+
'<section class="completion closing-message"><h2>Viele Teile machen ein Blatt leistungsfähig</h2><p>Ein Laubblatt ist viel mehr als eine dünne grüne Fläche. Seine Schichten schützen es, lassen Licht zu den Chloroplasten gelangen und ermöglichen den Austausch und Transport von Stoffen. Jeder Bestandteil erfüllt eine bestimmte Aufgabe. Erst ihr Zusammenspiel macht es möglich, dass das Blatt seine Aufgaben für die Pflanze erfüllt.</p><p><strong>Du kennst jetzt den Aufbau eines Laubblattes und weißt, warum seine Teile wichtig sind.</strong></p></section>'+actions('lueckentext','zusatz','Zu den Zusatzaufgaben');}

function render(focus=false){const route=location.hash.slice(1)||'start';if(foodOrder.includes(route)&&foodOrder.indexOf(route)>1&&!networkComplete()){location.hash='nahrung-netz';return;}const pages={start:home,unterricht:unterrichtHome,zusatz:zusatzHome,entdecken:entry,elektronen:()=>microscopy('elektronen'),licht:()=>microscopy('licht'),zuordnen:assignmentPage,fragen:questionPage,lueckentext:clozePage,abschluss:closingPage};const page=pages[route]||treePages[route]||foodPages[route]||sunPages[route]||home;root.innerHTML=(order.includes(route)?steps(route):treeOrder.includes(route)?treeSteps(route):foodOrder.includes(route)?foodSteps(route):sunOrder.includes(route)?sunSteps(route):'')+page();const nav=document.querySelector('.home-link');if(nav){const target=foodOrder.includes(route)?'unterricht':(order.includes(route)||treeOrder.includes(route)||sunOrder.includes(route))?'zusatz':'start';nav.href='#'+target;nav.textContent=target==='unterricht'?'Unterrichtsinhalte':target==='zusatz'?'Zusatzaufgaben':'Startseite';}if(focus){root.querySelector('h1')?.focus({preventScroll:true});window.scrollTo(0,0);}}
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){navigate(b.dataset.go);return;}if(b.dataset.term){state.selected=b.dataset.term;render();root.querySelector('[data-term="'+state.selected+'"]')?.focus();return;}if(b.dataset.slot!==undefined){if(!state.selected){const d=root.querySelector('.description');d.innerHTML='<h3>Zuerst einen Begriff wählen</h3><p>Klicke rechts auf einen Begriff und lies seine Beschreibung.</p>';return;}const i=Number(b.dataset.slot);assign(i,state.selected);render();root.querySelector('[data-slot="'+i+'"]')?.focus();return;}if(b.dataset.check){if(b.dataset.check==='assignment')state.assignmentChecked=true;if(b.dataset.check==='questions')state.questionsChecked=true;if(b.dataset.check==='cloze')state.clozeChecked=true;render();root.querySelector('[data-check="'+b.dataset.check+'"]')?.focus();}});
root.addEventListener('change',e=>{const el=e.target;if(el.dataset.question!==undefined){state.questions[el.dataset.question]=el.value;state.questionsChecked=false;root.querySelectorAll('[data-question]').forEach(s=>s.className='');root.querySelectorAll('.answer-note,.feedback').forEach(s=>s.textContent='');}if(el.dataset.gap!==undefined){const i=el.dataset.gap;state.cloze[i]=el.value;state.clozeChecked=false;render();root.querySelector('[data-gap="'+i+'"]')?.focus();}});

window.addEventListener('hashchange',()=>render(true));render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'assign_leaf_terms',title:'Blattbegriffe zuordnen',description:'Ordnet ausgewählte Blattbegriffe den Stellen 1 bis 7 zu und öffnet die sichtbare Zuordnungsaufgabe. Prüft die Lösungen noch nicht.',inputSchema:{type:'object',properties:{assignments:{type:'array',items:{type:'object',properties:{position:{type:'integer',minimum:1,maximum:7},termId:{type:'string',enum:terms.map(t=>t.id)}},required:['position','termId'],additionalProperties:false}}},required:['assignments'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.assignments)||input.assignments.some(a=>!a||!Number.isInteger(a.position)||a.position<1||a.position>7||!byId(a.termId)))throw Error('Ungültige Zuordnung');const positions=input.assignments.map(a=>a.position),ids=input.assignments.map(a=>a.termId);if(new Set(positions).size!==positions.length||new Set(ids).size!==ids.length)throw Error('Doppelte Stelle oder doppelter Begriff');input.assignments.forEach(a=>assign(a.position-1,a.termId));location.hash='zuordnen';render();return {assignments:Object.entries(state.assigned).map(([i,id])=>({position:Number(i)+1,termId:id})),checked:false};}})).catch(()=>{});}catch{}}


installTreeEvents();
installFoodEvents();

installSunEvents();
