'use strict';

const foodOrder=['nahrung-start','nahrung-netz','nahrung-auswerten','nahrung-erklaeren','nahrung-folgen','nahrung-abschluss'];
const foodLabels=['Vorbereiten','Netz bauen','Auswerten','Erklären','Folgen','Abschluss'];
const organisms=[
  {id:'eiche',name:'Eiche',image:'M1_01_Eiche.png',kind:'Produzent'},
  {id:'brombeere',name:'Brombeere',image:'M1_02_Brombeere.png',kind:'Produzent'},
  {id:'raupe',name:'Raupe',image:'M1_03_Raupe.png',kind:'Erstkonsument'},
  {id:'waldmaus',name:'Waldmaus',image:'M1_04_Waldmaus.png',kind:'Erstkonsument'},
  {id:'reh',name:'Reh',image:'M1_05_Reh.png',kind:'Erstkonsument'},
  {id:'buntspecht',name:'Buntspecht',image:'M1_06_Buntspecht.png',kind:'Zweitkonsument'},
  {id:'waldkauz',name:'Waldkauz',image:'M1_07_Waldkauz.png',kind:'Zweitkonsument'},
  {id:'rotfuchs',name:'Rotfuchs',image:'M1_08_Rotfuchs.png',kind:'Zweitkonsument'}
];
const slots=[
  {id:'second-1',kind:'Zweitkonsument',x:17,y:18},{id:'second-2',kind:'Zweitkonsument',x:50,y:18},{id:'second-3',kind:'Zweitkonsument',x:83,y:18},
  {id:'first-1',kind:'Erstkonsument',x:17,y:50},{id:'first-2',kind:'Erstkonsument',x:50,y:50},{id:'first-3',kind:'Erstkonsument',x:83,y:50},
  {id:'producer-1',kind:'Produzent',x:32,y:82},{id:'producer-2',kind:'Produzent',x:68,y:82}
];
const defaultPlacements={'producer-1':'eiche','producer-2':'brombeere','first-1':'raupe','first-2':'waldmaus','first-3':'reh','second-1':'waldkauz','second-2':'buntspecht','second-3':'rotfuchs'};
const expectedFoodEdges=new Set([
  'eiche>raupe','eiche>waldmaus','eiche>reh','brombeere>waldmaus','brombeere>reh','brombeere>rotfuchs',
  'raupe>buntspecht','waldmaus>waldkauz','waldmaus>rotfuchs'
]);
const organismById=id=>organisms.find(o=>o.id===id);
const slotById=id=>slots.find(s=>s.id===id);
const foodState={placements:{},placementSelected:null,placementChecked:false,connections:new Set(),networkChecked:false,networkAttempts:0,analysis:{},analysisChecked:false,why:{},whyChecked:false,whyOrder:null,consequences:{},consequencesChecked:false,consequenceOrder:null};

function foodSteps(route){return '<nav class="steps" aria-label="Lernschritte zum Nahrungsnetz">'+foodOrder.map((s,i)=>i>1&&!networkComplete()?'<span class="step step-locked" aria-disabled="true">'+(i+1)+' · '+foodLabels[i]+'</span>':'<a class="step" href="#'+s+'" '+(route===s?'aria-current="step"':'')+'>'+(i+1)+' · '+foodLabels[i]+'</a>').join('')+'</nav>';}
function foodActions(previous,next,nextLabel='Weiter',showNext=true){return '<div class="actions"><a class="button secondary" href="#'+previous+'">← Zurück</a>'+(showNext?'<a class="button" href="#'+next+'">'+nextLabel+' →</a>':'')+'</div>';}
function shuffleFoodOptions(options,key){if(!foodState[key]){const ids=options.map(o=>o.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]];}foodState[key]=ids;}return foodState[key].map(id=>options.find(o=>o.id===id));}
function placementForOrg(id){return slots.find(s=>foodState.placements[s.id]===id);}
function placementsComplete(){return Object.keys(foodState.placements).length===organisms.length&&organisms.every(o=>placementForOrg(o.id));}
function placementsValid(){return placementsComplete()&&slots.every(s=>organismById(foodState.placements[s.id])?.kind===s.kind);}
function edgesValid(){const edges=[...foodState.connections];return edges.length===expectedFoodEdges.size&&edges.every(e=>expectedFoodEdges.has(e));}
function networkComplete(){return foodState.placementChecked&&foodState.networkChecked&&placementsValid()&&edgesValid();}

function foodStart(){return heading('Thema 03 · Nahrungsnetzwerke','Wer frisst wen?','Lege das Arbeitsblatt und einen Stift bereit. Das Programm führt dich Schritt für Schritt durch die Aufgaben 1 bis 5.')+
  '<div class="food-intro"><section class="panel"><span class="tag">Die wichtigste Regel</span><div class="arrow-rule"><span>Nahrung</span><span class="rule-arrow" aria-hidden="true">→</span><span>Fresser</span></div><p>Der Pfeil beginnt bei der Nahrung und zeigt zu dem Lebewesen, das sie frisst. Beispiel: <strong>Eiche → Raupe</strong>, weil die Raupe Eichenblätter frisst.</p><div class="note"><strong>Arbeite mit dem Blatt:</strong> Übertrage deine Ergebnisse jeweils dann, wenn das Programm dich dazu auffordert.</div></section><section><h2>Deine acht Organismenkarten</h2><div class="food-card-strip">'+organisms.map(o=>'<figure><img src="assets/'+o.image+'" alt="Organismenkarte '+o.name+'"><figcaption>'+o.name+'</figcaption></figure>').join('')+'</div></section></div>'+foodActions('unterricht','nahrung-netz','Netz bauen');}

function foodCard(o,placed=false){return '<button class="food-card '+(placed?'placed-card ':'bank-card ')+(foodState.placementSelected===o.id?'selected':'')+'" data-food-bank-card="'+o.id+'" draggable="'+(!placed)+'" aria-pressed="'+(foodState.placementSelected===o.id)+'"><img src="assets/'+o.image+'" alt="Organismenkarte '+o.name+'"><span>'+o.name+'</span></button>';}
function shortenLine(a,b,distance){const dx=b.x-a.x,dy=b.y-a.y,length=Math.hypot(dx,dy)||1;return {x:b.x-dx/length*distance,y:b.y-dy/length*distance};}
function foodArrow(edge,small=false){const [sourceId,targetId]=edge.split('>'),sourceSlot=placementForOrg(sourceId),targetSlot=placementForOrg(targetId);if(!sourceSlot||!targetSlot)return '';const scaleY=small?4.6:6.2,a={x:sourceSlot.x*10,y:sourceSlot.y*scaleY},b={x:targetSlot.x*10,y:targetSlot.y*scaleY},start=shortenLine(b,a,small?55:72),end=shortenLine(a,b,small?58:78),wrong=foodState.networkChecked&&!expectedFoodEdges.has(edge);return '<path class="food-arrow '+(wrong?'wrong':'')+'" d="M '+start.x+' '+start.y+' L '+end.x+' '+end.y+'" marker-end="url(#'+(wrong?'arrow-wrong':'arrow-ok')+')" />';}
function boardMarkers(){return '<defs><marker id="arrow-ok" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker><marker id="arrow-wrong" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="8" markerHeight="8" orient="auto"><path d="M 0 0 L 10 5 L 0 10 z"/></marker></defs>';}
function foodBoard(readonly=false){const edges=[...foodState.connections];return '<div class="food-board '+(readonly?'food-board-recap':'')+'" aria-label="'+(readonly?'Dein gebautes Nahrungsnetz':'Arbeitsfläche mit drei Ernährungsebenen')+'"><div class="food-level second-level"><span class="level-label">Zweitkonsumenten</span></div><div class="food-level first-level"><span class="level-label">Erstkonsumenten</span></div><div class="food-level producer-level"><span class="level-label">Produzenten</span></div><svg viewBox="0 0 1000 '+(readonly?'460':'620')+'" aria-hidden="true">'+boardMarkers()+edges.map(e=>foodArrow(e,readonly)).join('')+'</svg>'+slots.map(s=>{const org=organismById(foodState.placements[s.id]),wrong=foodState.placementChecked&&org&&org.kind!==s.kind;return '<div class="food-drop '+(org?'filled ':'')+(wrong?'wrong ':'')+'" data-food-slot="'+s.id+'" style="left:'+s.x+'%;top:'+s.y+'%" tabindex="'+(readonly?'-1':'0')+'" aria-label="Ablagefeld '+s.kind+(org?', belegt mit '+org.name:'')+'">'+(org?'<div class="food-card placed-card" data-placed-organism="'+org.id+'" '+(readonly?'':'data-food-bank-card="'+org.id+'" draggable="true"')+'><img src="assets/'+org.image+'" alt="Organismenkarte '+org.name+'"><span>'+org.name+'</span></div>':'<span class="drop-placeholder">Karte ablegen</span>')+'</div>';}).join('')+'</div>';}
function edgeLabel(edge){const [a,b]=edge.split('>');return organismById(a).name+' → '+organismById(b).name;}
function placeFoodCard(orgId,slotId){const slot=slotById(slotId),org=organismById(orgId);if(!slot||!org)return;const former=placementForOrg(orgId),displaced=foodState.placements[slotId];if(former)delete foodState.placements[former.id];foodState.placements[slotId]=orgId;if(displaced&&former)foodState.placements[former.id]=displaced;foodState.placementSelected=null;foodState.placementChecked=false;foodState.networkChecked=false;foodState.connections.clear();}
function placementFeedback(){if(!foodState.placementChecked)return '';if(placementsValid())return '<div class="feedback" role="status"><span class="ok">✓ Alle Karten liegen auf der richtigen Ebene. Jetzt kannst du die Nahrungspfeile setzen.</span></div>';const placed=Object.keys(foodState.placements).length;return '<div class="feedback" role="status"><span class="bad">Noch nicht richtig: '+placed+' von 8 Karten sind abgelegt. Prüfe Produzenten, Erstkonsumenten und Zweitkonsumenten.</span></div>';}
function networkFeedback(){if(!foodState.networkChecked)return '';const edges=[...foodState.connections],right=edges.filter(e=>expectedFoodEdges.has(e)).length,wrong=edges.length-right,missing=expectedFoodEdges.size-right;if(placementsValid()&&!wrong&&!missing)return '<div class="completion"><h2>Dein Nahrungsnetz stimmt!</h2><p>Alle Karten und alle neun Nahrungsbeziehungen sind richtig. Übertrage die Pfeile jetzt in <strong>Aufgabe 1</strong> auf dein Arbeitsblatt.</p></div>';let hint=foodState.networkAttempts>1?'Achte besonders auf Eicheln, Beeren, Mäuse und darauf, wer Raupen frisst.':'Lies die Texte auf den Karten noch einmal.';return '<div class="feedback network-feedback" role="status"><span class="bad">'+right+' von 9 richtigen Pfeilen. '+(wrong?wrong+' Pfeil'+(wrong===1?' passt':'e passen')+' nicht. ':'')+(missing?missing+' richtige Verbindung'+(missing===1?' fehlt.':'en fehlen.'):'')+'</span><p>'+hint+' Falsche Pfeile sind rot markiert und können unten entfernt werden.</p></div>';}

function foodNetwork(){const edges=[...foodState.connections],unplaced=organisms.filter(o=>!placementForOrg(o.id)),ready=placementsValid();return heading('Aufgabe 1 · Nahrungsnetz bauen','Baue dein eigenes Nahrungsnetz','Ziehe zuerst jede Karte in ein passendes Ablagefeld. Innerhalb einer Ebene entscheidest du selbst über die Reihenfolge. Verbinde danach Nahrung und Fresser.')+
  '<section class="card-bank panel"><h2>Organismenkarten</h2><p>Ziehe eine Karte auf ein Ablagefeld. Du kannst sie auch anklicken und anschließend das gewünschte Feld wählen.</p><div class="bank-cards">'+(unplaced.length?unplaced.map(o=>foodCard(o)).join(''):'<p class="ok">Alle Karten sind abgelegt.</p>')+'</div></section><div class="network-layout"><section>'+foodBoard(false)+'</section><aside class="panel network-tools"><h2>'+(ready?'Nahrungspfeile setzen':'Karten einordnen')+'</h2><p>'+(ready?(foodState.placementSelected?'Klicke nun auf den Fresser.':'Klicke eine abgelegte Karte als Nahrung und danach den passenden Fresser an.'):'Ordne erst alle Karten den drei Ernährungsebenen zu und prüfe deine Anordnung.')+'</p><button class="button" data-food-check="placement">Karten prüfen</button>'+placementFeedback()+(ready?'<div class="edge-list">'+(edges.length?edges.map(e=>'<button class="edge-chip '+(foodState.networkChecked&&!expectedFoodEdges.has(e)?'wrong':'')+'" data-remove-edge="'+e+'" title="Verbindung entfernen">'+edgeLabel(e)+' <span aria-hidden="true">×</span></button>').join(''):'<p class="subtle">Noch kein Pfeil gesetzt.</p>')+'</div><button class="button" data-food-check="network">Netz prüfen</button><button class="text-button" data-food-reset="network">Alle Pfeile löschen</button>'+networkFeedback():'')+'</aside></div>'+foodActions('nahrung-start','nahrung-auswerten','Aufgaben 2 und 3',networkComplete());}

function foodSelect(id,value){return '<select id="'+id+'" data-food-analysis="'+id+'"><option value="">Bitte wählen …</option>'+organisms.map(o=>'<option value="'+o.id+'" '+(value===o.id?'selected':'')+'>'+o.name+'</option>').join('')+'</select>';}
function analysisValidity(prefix){const a=foodState.analysis,org=a[prefix+'Org'],type=a[prefix+'Type'],reason=a[prefix+'Reason'];if(prefix==='q2')return ['waldmaus','reh','rotfuchs'].includes(org)&&type==='Konsument'&&reason==='eats';const expectedType=['eiche','brombeere'].includes(org)?'Produzent':org==='waldmaus'?'Konsument':'';return ['eiche','brombeere','waldmaus'].includes(org)&&type===expectedType&&reason===(expectedType==='Produzent'?'makes':'eats');}
function analysisBlock(prefix,title,prompt){const a=foodState.analysis,valid=analysisValidity(prefix);return '<section class="panel analysis-card '+(foodState.analysisChecked?(valid?'answer-correct':'answer-wrong'):'')+'"><span class="tag">'+title+'</span><h2>'+prompt+'</h2><label for="'+prefix+'Org">Organismus</label>'+foodSelect(prefix+'Org',a[prefix+'Org'])+'<fieldset><legend>Produzent oder Konsument?</legend><label><input type="radio" name="'+prefix+'Type" data-food-analysis="'+prefix+'Type" value="Produzent" '+(a[prefix+'Type']==='Produzent'?'checked':'')+'> Produzent</label><label><input type="radio" name="'+prefix+'Type" data-food-analysis="'+prefix+'Type" value="Konsument" '+(a[prefix+'Type']==='Konsument'?'checked':'')+'> Konsument</label></fieldset><fieldset><legend>Passende Begründung</legend><label><input type="radio" name="'+prefix+'Reason" data-food-analysis="'+prefix+'Reason" value="makes" '+(a[prefix+'Reason']==='makes'?'checked':'')+'> stellt mithilfe von Licht energiereiche Stoffe her</label><label><input type="radio" name="'+prefix+'Reason" data-food-analysis="'+prefix+'Reason" value="eats" '+(a[prefix+'Reason']==='eats'?'checked':'')+'> nimmt energiereiche Stoffe als Nahrung auf</label></fieldset>'+(foodState.analysisChecked?'<p class="answer-note">'+(valid?'✓ Diese Auswahl ist möglich. Übertrage Organismus, Zuordnung und Begründung auf dein Arbeitsblatt.':'Noch nicht passend. Zähle die Pfeilspitzen beziehungsweise Pfeilanfänge in deinem Netz und prüfe die Begründung.')+'</p>':'')+'</section>';}
function foodAnalysis(){const score=['q2','q3'].filter(analysisValidity).length;return heading('Aufgaben 2 und 3 · Netz auswerten','Was verraten die Pfeile?','Nutze dein selbst gebautes Netz. Mehrere Pfeile bedeuten: Ein Organismus hat mehrere Nahrungsquellen oder dient mehreren Fressern als Nahrung.')+'<section class="network-recap"><h2>Dein Nahrungsnetz</h2>'+foodBoard(true)+'</section><div class="analysis-grid">'+analysisBlock('q2','Aufgabe 2','Bei welchem Organismus kommen mehrere Pfeile an?')+analysisBlock('q3','Aufgabe 3','Von welchem Organismus gehen mehrere Pfeile ab?')+'</div><div class="actions"><button class="button" data-food-check="analysis">Antworten prüfen</button><span class="feedback" role="status">'+(foodState.analysisChecked?score+' von 2 Antworten vollständig passend.':'')+'</span></div><div class="note"><strong>Denkhilfe:</strong> Eine Pfeilspitze zeigt zum Fresser. Ein Pfeilanfang liegt bei der Nahrung.</div>'+foodActions('nahrung-netz','nahrung-erklaeren','Aufgabe 4');}

const whyOptions=[
  {id:'many-foods',text:'Ein Organismus kann verschiedene Nahrungsquellen haben.',correct:true},{id:'many-eaters',text:'Ein Organismus kann von mehreren anderen gefressen werden.',correct:true},
  {id:'all-in-chain',text:'Eine einzige Nahrungskette zeigt bereits alle Beziehungen im Wald.',correct:false},{id:'arrow-size',text:'Die Anzahl der Pfeile zeigt, wie groß ein Lebewesen ist.',correct:false}
];
const consequenceOptions=[
  {id:'owl-food',text:'Der Waldkauz findet weniger Nahrung.',correct:true},{id:'plant-food',text:'Eicheln und Beeren werden von Waldmäusen seltener gefressen.',correct:true},
  {id:'more-owls',text:'Es gibt sofort mehr Waldkäuze, weil weniger Mäuse da sind.',correct:false},{id:'no-change',text:'Im Nahrungsnetz ändert sich nichts, weil nur eine Art betroffen ist.',correct:false}
];
function choiceList(options,stateKey,orderKey){return '<div class="choice-list">'+shuffleFoodOptions(options,orderKey).map(o=>'<label class="choice '+(foodState[stateKey+'Checked']?(Boolean(foodState[stateKey][o.id])===o.correct?'choice-correct':'choice-wrong'):'')+'"><input type="checkbox" data-food-choice="'+stateKey+'" value="'+o.id+'" '+(foodState[stateKey][o.id]?'checked':'')+'> <span>'+o.text+'</span></label>').join('')+'</div>';}
function foodWhy(){const selected=whyOptions.filter(o=>foodState.why[o.id]),correct=selected.length===2&&selected.every(o=>o.correct);return heading('Aufgabe 4 · Begründen','Warum ist ein Netz genauer?','Wähle die zwei Aussagen, die dir beim Formulieren deiner Antwort helfen.')+'<section class="panel explain-panel">'+choiceList(whyOptions,'why','whyOrder')+'<button class="button" data-food-check="why">Aussagen prüfen</button>'+(foodState.whyChecked?'<div class="feedback" role="status">'+(correct?'<span class="ok">✓ Richtig. Formuliere nun auf dem Arbeitsblatt: Ein Nahrungsnetz beschreibt den Wald besser, weil …</span>':'<span class="bad">Noch nicht. Wähle genau zwei Aussagen, die echte Nahrungsbeziehungen beschreiben.</span>')+'</div>':'')+'</section>'+foodActions('nahrung-auswerten','nahrung-folgen','Aufgabe 5');}
function foodConsequences(){const selected=consequenceOptions.filter(o=>foodState.consequences[o.id]),correct=selected.length===2&&selected.every(o=>o.correct);return heading('Aufgabe 5 · Folgen vorhersagen','Die Waldmäuse werden selten','Verfolge im Netz zuerst alle Pfeile, die bei der Waldmaus beginnen oder bei ihr ankommen. Wähle dann zwei mögliche Folgen.')+'<div class="scenario-grid"><section class="panel mouse-card"><img src="assets/M1_04_Waldmaus.png" alt="Organismenkarte Waldmaus"><div><span class="tag">Was-wäre-wenn?</span><h2>Weniger Waldmäuse</h2><p>Denke in beide Richtungen: Was geschieht mit ihrer Nahrung? Was geschieht mit ihren Fressern?</p></div></section><section class="panel">'+choiceList(consequenceOptions,'consequences','consequenceOrder')+'<button class="button" data-food-check="consequences">Folgen prüfen</button>'+(foodState.consequencesChecked?'<div class="feedback" role="status">'+(correct?'<span class="ok">✓ Beide Folgen lassen sich direkt aus deinem Nahrungsnetz ableiten. Schreibe sie in eigenen Sätzen auf das Arbeitsblatt.</span>':'<span class="bad">Noch nicht. Suche die Pfeile an der Waldmaus und überlege, wer von weniger Mäusen betroffen ist.</span>')+'</div>':'')+'</section></div>'+foodActions('nahrung-erklaeren','nahrung-abschluss','Zum Abschluss');}

function foodClosing(){return heading('Abschluss · Arbeitsblatt prüfen','Dein Nahrungsnetz ist fertig','Nimm dir zwei Minuten für den Abschlusscheck. Danach kannst du dein Arbeitsblatt abgeben.')+'<div class="finish-grid"><section class="completion"><h2>Das solltest du jetzt können</h2><ul><li>Pfeile nach der Regel <strong>Nahrung → Fresser</strong> einzeichnen.</li><li>Produzenten und Konsumenten unterscheiden und begründen.</li><li>erklären, warum ein Nahrungsnetz genauer ist als eine Nahrungskette.</li><li>Folgen einer Veränderung im Netz vorhersagen.</li></ul></section><section class="panel worksheet-check"><h2>Steht alles auf deinem Blatt?</h2><ol><li>Das Nahrungsnetz mit allen Pfeilen</li><li>Ein Organismus mit mehreren ankommenden Pfeilen</li><li>Ein Organismus mit mehreren abgehenden Pfeilen</li><li>Deine Erklärung zum Nahrungsnetz</li><li>Zwei mögliche Folgen bei seltenen Waldmäusen</li></ol><p class="ok">✓ Dein digitales Netz wurde vollständig geprüft.</p></section></div>'+foodActions('nahrung-folgen','unterricht','Zu den Unterrichtsinhalten');}

const foodPages={'nahrung-start':foodStart,'nahrung-netz':foodNetwork,'nahrung-auswerten':foodAnalysis,'nahrung-erklaeren':foodWhy,'nahrung-folgen':foodConsequences,'nahrung-abschluss':foodClosing};

function selectPlacedCard(id){if(!placementsValid())return;if(!foodState.placementSelected)foodState.placementSelected=id;else if(foodState.placementSelected===id)foodState.placementSelected=null;else{foodState.connections.add(foodState.placementSelected+'>'+id);foodState.placementSelected=null;foodState.networkChecked=false;}}
function installFoodEvents(){
  root.addEventListener('click',e=>{const slot=e.target.closest('[data-food-slot]'),bank=e.target.closest('[data-food-bank-card]'),placed=e.target.closest('[data-placed-organism]'),button=e.target.closest('button');
    if(bank&&!placementsValid()){foodState.placementSelected=foodState.placementSelected===bank.dataset.foodBankCard?null:bank.dataset.foodBankCard;render();return;}
    if(slot&&foodState.placementSelected&&!placementsValid()){placeFoodCard(foodState.placementSelected,slot.dataset.foodSlot);render();return;}
    if(placed&&placementsValid()){selectPlacedCard(placed.dataset.placedOrganism);render();return;}
    if(!button)return;
    if(button.dataset.removeEdge){foodState.connections.delete(button.dataset.removeEdge);foodState.networkChecked=false;render();return;}
    if(button.dataset.foodReset==='network'){foodState.connections.clear();foodState.placementSelected=null;foodState.networkChecked=false;render();return;}
    if(button.dataset.foodCheck){const group=button.dataset.foodCheck;if(group==='placement')foodState.placementChecked=true;if(group==='network'){foodState.networkChecked=true;foodState.networkAttempts++;}if(group==='analysis')foodState.analysisChecked=true;if(group==='why')foodState.whyChecked=true;if(group==='consequences')foodState.consequencesChecked=true;render();root.querySelector('[data-food-check="'+group+'"]')?.focus();}
  });
  root.addEventListener('dragstart',e=>{const card=e.target.closest('[data-food-bank-card]');if(!card?.dataset?.foodBankCard)return;e.dataTransfer.setData('text/plain',card.dataset.foodBankCard);e.dataTransfer.effectAllowed='move';card.classList.add('dragging');});
  root.addEventListener('dragend',e=>e.target.closest('[data-food-bank-card]')?.classList.remove('dragging'));
  root.addEventListener('dragover',e=>{const slot=e.target.closest('[data-food-slot]');if(!slot)return;e.preventDefault();slot.classList.add('drop-hover');});
  root.addEventListener('dragleave',e=>e.target.closest('[data-food-slot]')?.classList.remove('drop-hover'));
  root.addEventListener('drop',e=>{const slot=e.target.closest('[data-food-slot]');if(!slot?.dataset?.foodSlot)return;e.preventDefault();slot.classList.remove('drop-hover');const id=e.dataTransfer.getData('text/plain');if(organismById(id)){placeFoodCard(id,slot.dataset.foodSlot);render();}});
  root.addEventListener('keydown',e=>{const slot=e.target.closest('[data-food-slot]');if(slot&&(e.key==='Enter'||e.key===' ')&&foodState.placementSelected&&!placementsValid()){e.preventDefault();placeFoodCard(foodState.placementSelected,slot.dataset.foodSlot);render();}});
  root.addEventListener('change',e=>{const el=e.target;if(el.dataset.foodAnalysis){foodState.analysis[el.dataset.foodAnalysis]=el.value;foodState.analysisChecked=false;render();}if(el.dataset.foodChoice){const group=el.dataset.foodChoice;foodState[group][el.value]=el.checked;foodState[group+'Checked']=false;render();}});
  if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'set_foodweb_connections',title:'Nahrungsnetz aufbauen',description:'Ordnet alle Karten richtig ein und setzt ausgewählte Pfeile. Die Richtung ist Nahrung zu Fresser.',inputSchema:{type:'object',properties:{connections:{type:'array',items:{type:'object',properties:{food:{type:'string',enum:organisms.map(o=>o.id)},eater:{type:'string',enum:organisms.map(o=>o.id)}},required:['food','eater'],additionalProperties:false}}},required:['connections'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.connections))throw Error('Ungültige Verbindungen');foodState.placements={...defaultPlacements};foodState.placementChecked=true;foodState.connections=new Set(input.connections.map(c=>c.food+'>'+c.eater));foodState.networkChecked=false;location.hash='nahrung-netz';render();return {connections:[...foodState.connections],checked:false};}})).catch(()=>{});}catch{}
}
}
