'use strict';
const sunOrder=['sonnenblatt','sonne-flaeche','sonne-querschnitt','sonne-erklaeren','sonne-anwenden','sonne-abschluss'];
const sunLabels=['Standort','Blattfläche','Querschnitt','Erklären','Anwenden','Abschluss'];
const sunState={location:{},area:{},tissue:{},compare:{},explain:{},apply:{},checked:{}};
const sunAnswer={
location:{a:'viel',b:'wenig'},area:{a:'klein',b:'gross'},tissue:{a:'palisade',b:'palisade'},
compare:{thick:'a',layers:'a',single:'b'},
explain:{0:'1',1:'2',2:'0'},
apply:{type1:'schatten',reason1:'1',type2:'sonne',reason2:'0'}};
function sunSteps(r){return '<nav class="steps" aria-label="Lernschritte Sonnenblatt und Schattenblatt">'+sunOrder.map((s,i)=>'<a class="step" href="#'+s+'" '+(r===s?'aria-current="step"':'')+'>'+(i+1)+' · '+sunLabels[i]+'</a>').join('')+'</nav>';}
function sunHead(title,intro){return heading('Vertiefung · Der Aufbau eines Laubblattes',title,intro);}
function sunCorrect(group){return Object.entries(sunAnswer[group]).filter(([k,v])=>sunState[group][k]===v).length;}
function sunFeedback(group){const n=Object.keys(sunAnswer[group]).length,score=sunCorrect(group);return '<div role="status" class="feedback">'+(sunState.checked[group]?(score===n?'<span class="ok">✓ Alles richtig!</span>':'<span class="bad">'+score+' von '+n+' richtig. Überprüfe die markierten Antworten.</span>'):'')+'</div>';}
function sunSelect(group,key,options,label){const value=sunState[group][key];return '<label class="sun-field">'+label+'<select data-sun-group="'+group+'" data-sun-key="'+key+'" class="'+(sunState.checked[group]?(value===sunAnswer[group][key]?'correct':'wrong'):'')+'"><option value="">Bitte wählen …</option>'+options.map(([id,text])=>'<option value="'+id+'" '+(value===id?'selected':'')+'>'+text+'</option>').join('')+'</select></label>';}
function sunCheck(group,label='Antworten prüfen'){return '<button class="button" data-sun-check="'+group+'">'+label+'</button>'+sunFeedback(group);}
function sunStart(){return sunHead('Sonnenblatt und Schattenblatt','Vergleiche, wie Blätter an unterschiedliche Lichtverhältnisse angepasst sind. Der Grundbauplan des Laubblattes bleibt dabei erhalten.')+
'<p class="sun-prerequisite"><strong>Bearbeite zuerst „Der Aufbau eines Laubblattes“.</strong> Du brauchst die Begriffe Epidermis, Palisadengewebe und Chloroplasten. <a href="#entdecken">Zum vorherigen Thema</a></p>'+
'<div class="lead-grid"><figure class="panel" style="margin:0"><div class="tree-figure"><img src="assets/baum.png" alt="Symbolbild eines Baumes: Standort A außen oben in der Krone, Standort B im Inneren der Krone"><span class="root-mark" style="left:65%;top:16%">A</span><span class="root-mark" style="left:48%;top:42%">B</span></div><figcaption class="caption">Symbolbild: zwei Standorte in einer Baumkrone. Der folgende Blattvergleich zeigt die Buche.</figcaption></figure><section class="panel"><h2>Wo kommt mehr Licht an?</h2><p>Außen und oben trifft Sonnenlicht unmittelbar auf die Blätter. Im Inneren wird ein Teil des Lichts bereits von anderen Blättern abgefangen.</p>'+sunSelect('location','a',[['wenig','Wenig Licht'],['viel','Viel Licht']],'Standort A · außen und oben')+sunSelect('location','b',[['wenig','Wenig Licht'],['viel','Viel Licht']],'Standort B · im Inneren')+sunCheck('location')+'<p class="sun-question">Sehen die Blätter an beiden Standorten gleich aus?</p></section></div>'+actions('zusatz','sonne-flaeche');}
function sunArea(){const revealed=sunState.checked.area&&sunCorrect('area')===2;return sunHead('Vergleiche die Blattflächen','Betrachte die beiden Buchenblätter. Beide sind im selben Bildmaßstab dargestellt. Ordne die Merkmale zu.')+
'<figure class="panel sun-image-panel"><div class="sun-pair-head"><h2>Blatt A'+(revealed?' · Sonnenblatt':'')+'</h2><h2>Blatt B'+(revealed?' · Schattenblatt':'')+'</h2></div><img class="micro-image" src="assets/sonne-schatten-blaetter.png" alt="Zwei Buchenblätter im Größenvergleich: Blatt A links, Blatt B rechts"><figcaption class="caption">Vereinfachte KI-Illustration eines typischen Größenunterschieds. Blattfarbe ist hier kein Unterscheidungsmerkmal.</figcaption></figure>'+
'<div class="sun-two"><section class="panel">'+sunSelect('area','a',[['gross','Größere Blattfläche'],['klein','Kleinere Blattfläche']],'Blatt A')+'</section><section class="panel">'+sunSelect('area','b',[['gross','Größere Blattfläche'],['klein','Kleinere Blattfläche']],'Blatt B')+'</section></div>'+sunCheck('area','Vergleich prüfen')+
(revealed?'<p class="note">Bei der Buche sind <strong>Sonnenblätter</strong> typischerweise kleiner und fester. <strong>Schattenblätter</strong> sind größer und zarter. Auch im Inneren unterscheiden sie sich.</p>':'')+actions('sonnenblatt','sonne-querschnitt','Mit der Lupe ins Blatt');}
const sunBands={a:[['epidermis','1',24.5],['palisade','2',35],['schwamm','3',64]],b:[['epidermis','1',24.5],['palisade','2',34],['schwamm','3',49]]};
function sunSections(){return sunHead('Vergleiche das Palisadengewebe','Wähle zuerst in jedem Querschnitt das Palisadengewebe aus. Die Ziffern markieren Gewebebereiche.')+
'<figure class="panel sun-image-panel"><div class="sun-pair-head"><h2>A · Sonnenblatt</h2><h2>B · Schattenblatt</h2></div><div class="sun-section-image"><img src="assets/sonne-schatten-querschnitte.png" alt="Querschnitte im gemeinsamen Bildmaßstab: dickes Sonnenblatt links und dünnes Schattenblatt rechts">'+Object.entries(sunBands).map(([side,bands])=>bands.map(([id,n,y])=>'<button class="sun-band '+(sunState.tissue[side]===id?'selected ':'')+(sunState.checked.tissue&&sunState.tissue[side]===id?(id==='palisade'?'right':'incorrect'):'')+'" style="left:'+(side==='a'?25:75)+'%;top:'+y+'%" data-sun-side="'+side+'" data-sun-tissue="'+id+'" aria-label="Blatt '+side.toUpperCase()+', Gewebebereich '+n+'" aria-pressed="'+(sunState.tissue[side]===id)+'">'+n+'</button>').join('')).join('')+'</div><figcaption class="caption">Vereinfachte KI-Schemata im gemeinsamen Bildmaßstab. Die Unterschiede sind beispielhaft für die Buche dargestellt.</figcaption></figure>'+sunCheck('tissue','Palisadengewebe prüfen')+
(sunState.checked.tissue?'<p class="note">'+(sunCorrect('tissue')===2?'Richtig: Im Sonnenblatt erkennst du zwei übereinanderliegende Reihen länglicher Palisadenzellen. Im Schattenblatt siehst du eine Reihe.':'Suche nach länglichen, dicht stehenden Zellen mit vielen Chloroplasten direkt unter der oberen Epidermis.')+'</p>':'')+
'<section class="panel sun-compare"><h2>Halte die Unterschiede fest</h2>'+sunSelect('compare','thick',[['b','B · Schattenblatt'],['a','A · Sonnenblatt']],'Welches Blatt ist dicker?')+sunSelect('compare','layers',[['b','B · Schattenblatt'],['a','A · Sonnenblatt']],'Welches Palisadengewebe hat hier mehrere Zellschichten?')+sunSelect('compare','single',[['b','B · Schattenblatt'],['a','A · Sonnenblatt']],'Welches Palisadengewebe hat hier nur eine Zellschicht?')+sunCheck('compare','Vergleich prüfen')+'</section>'+actions('sonne-flaeche','sonne-erklaeren');}
const sunQuestions=[
{q:'Welchen Vorteil hat eine große Blattfläche im Schatten?',choices:['Sie lässt mehr Licht durch die darüberliegenden Blätter hindurch.','Sie kann mehr von dem wenigen verfügbaren Licht auffangen.','Sie ersetzt die Chloroplasten bei der Fotosynthese.'],why:'Eine größere Fläche kann mehr Licht auffangen. Die Fotosynthese findet weiterhin in den Chloroplasten statt.'},
{q:'Warum passt stark ausgeprägtes Palisadengewebe zu einem sonnigen Standort?',choices:['Es hält das Licht von den Chloroplasten fern.','Es nimmt Wasser direkt aus der Luft auf.','Es bietet Platz für viele chloroplastenreiche Zellen, die das reichliche Licht nutzen.'],why:'Bei viel Licht können viele chloroplastenreiche Zellen zur Fotosynthese beitragen.'},
{q:'Was haben Sonnenblatt und Schattenblatt gemeinsam?',choices:['Beide besitzen den Grundbauplan eines Laubblattes.','Beide besitzen immer gleich viele Palisadenzellschichten.','Beide brauchen gleich viel Licht, um Fotosynthese zu betreiben.'],why:'Der Grundbauplan ist gleich. Größe und Ausprägung der Gewebe unterscheiden sich.'}];
function sunRadio(group,key,q,choices){return '<fieldset class="panel sun-radio"><legend>'+q+'</legend>'+choices.map((t,i)=>'<label><input type="radio" name="'+group+key+'" data-sun-group="'+group+'" data-sun-key="'+key+'" value="'+i+'" '+(sunState[group][key]===String(i)?'checked':'')+'> <span>'+t+'</span></label>').join('')+(sunState.checked[group]?'<p class="answer-note '+(sunState[group][key]===sunAnswer[group][key]?'ok':'bad')+'">'+(sunState[group][key]===sunAnswer[group][key]?'✓ Richtig.':'✕ Prüfe deine Auswahl noch einmal.')+'</p>':'')+'</fieldset>';}
function sunExplain(){return sunHead('Bau und Lichtverhältnisse passen zusammen','Lies die Erklärung und wähle zu jeder Frage genau eine richtige Antwort.')+
'<section class="panel"><p>Im Schatten steht weniger Licht zur Verfügung. Eine größere Blattfläche hilft, dieses Licht aufzufangen. Schattenblätter können schon bei wenig Licht Fotosynthese betreiben.</p><p>In der Sonne steht viel Licht zur Verfügung. Ein stärker ausgeprägtes Palisadengewebe bietet Platz für viele chloroplastenreiche Zellen. Sonnenblätter sind häufig dicker und haben eine kleinere Blattfläche.</p></section><div class="sun-question-list">'+sunQuestions.map((q,i)=>sunRadio('explain',String(i),q.q,q.choices)+(sunState.checked.explain?'<p class="sun-explanation">'+q.why+'</p>':'')).join('')+'</div>'+sunCheck('explain')+actions('sonne-querschnitt','sonne-anwenden');}
function sunApply(){return sunHead('Erkennst du den Blatttyp?','Ordne die beiden Blattprofile zu und wähle jeweils die passende Begründung.')+
'<div class="sun-two"><section class="panel"><span class="tag">Blattprofil 1</span><h2>Große Fläche · dünnes Blatt</h2><p>Das Palisadengewebe besteht aus einer Zellschicht.</p>'+sunSelect('apply','type1',[['sonne','Sonnenblatt'],['schatten','Schattenblatt']],'Welcher Blatttyp passt?')+'</section><section class="panel"><span class="tag">Blattprofil 2</span><h2>Kleine Fläche · dickes Blatt</h2><p>Das Palisadengewebe besteht aus mehreren Zellschichten.</p>'+sunSelect('apply','type2',[['sonne','Sonnenblatt'],['schatten','Schattenblatt']],'Welcher Blatttyp passt?')+'</section></div>'+
sunRadio('apply','reason1','Begründe Blattprofil 1',['Eine große Blattfläche verhindert, dass Licht die Zellen erreicht.','Eine große Blattfläche hilft, wenig verfügbares Licht aufzufangen.','Ein dünnes Blatt besitzt keine Chloroplasten.'])+
sunRadio('apply','reason2','Begründe Blattprofil 2',['Viele chloroplastenreiche Palisadenzellen können reichlich Licht nutzen.','Mehr Palisadenzellschichten ersetzen die Versorgung mit Wasser.','Eine kleine Blattfläche beweist, dass das Blatt krank ist.'])+sunCheck('apply','Zuordnungen und Begründungen prüfen')+actions('sonne-erklaeren','sonne-abschluss');}
function sunClosing(){return sunHead('Gleicher Grundbauplan – unterschiedliche Ausprägung','Die Merkmale der Blätter passen zu den Lichtverhältnissen ihres Standorts.')+
'<div class="sun-table-wrap"><table class="sun-table"><thead><tr><th>Merkmal</th><th>Sonnenblatt</th><th>Schattenblatt</th></tr></thead><tbody><tr><th>Standort</th><td>Außen und oben in der Krone</td><td>Im Inneren der Krone</td></tr><tr><th>Licht</th><td>Viel</td><td>Wenig</td></tr><tr><th>Blattfläche</th><td>Eher kleiner</td><td>Eher größer</td></tr><tr><th>Blattdicke</th><td>Eher dicker</td><td>Eher dünner</td></tr><tr><th>Palisadengewebe</th><td>Stärker ausgeprägt, häufig mehrschichtig</td><td>Meist einschichtig</td></tr></tbody></table></div><p class="caption">Typischer Vergleich am Beispiel der Buche. Die genaue Ausprägung kann variieren.</p><section class="completion"><h2>Ein Baum kann unterschiedliche Blätter tragen</h2><p>Blattfläche und Gewebedicke können unterschiedlich ausgeprägt sein, obwohl der Grundbauplan gleich bleibt. So können Blätter desselben Baumes unter verschiedenen Lichtbedingungen Fotosynthese betreiben.</p></section>'+actions('sonne-anwenden','zusatz','Zu den Zusatzaufgaben');}
const sunPages={'sonnenblatt':sunStart,'sonne-flaeche':sunArea,'sonne-querschnitt':sunSections,'sonne-erklaeren':sunExplain,'sonne-anwenden':sunApply,'sonne-abschluss':sunClosing};
function installSunEvents(){root.addEventListener('change',e=>{const el=e.target,g=el.dataset.sunGroup,k=el.dataset.sunKey;if(!g||!sunAnswer[g]||!(k in sunAnswer[g]))return;sunState[g][k]=el.value;sunState.checked[g]=false;render();root.querySelector('[data-sun-group="'+g+'"][data-sun-key="'+k+'"]'+(el.type==='radio'?'[value="'+el.value+'"]':''))?.focus();});
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.sunCheck&&sunAnswer[b.dataset.sunCheck]){sunState.checked[b.dataset.sunCheck]=true;render();root.querySelector('[data-sun-check="'+b.dataset.sunCheck+'"]')?.focus();}if(b.dataset.sunSide&&['a','b'].includes(b.dataset.sunSide)&&['epidermis','palisade','schwamm'].includes(b.dataset.sunTissue)){sunState.tissue[b.dataset.sunSide]=b.dataset.sunTissue;sunState.checked.tissue=false;render();root.querySelector('[data-sun-side="'+b.dataset.sunSide+'"][data-sun-tissue="'+b.dataset.sunTissue+'"]')?.focus();}});}

