'use strict';
const treeOrder=['baum','baum-bauplan','baum-aufgaben','baum-wurzel','baum-check','baum-abschluss'];
const treeLabels=['Erkunden','Grundbauplan','Funktionen','Wurzellupe','Wissenscheck','Abschluss'];
const treeState={part:'',assigned:{},exploreChecked:false,plan:{},planChecked:false,functions:{},functionsChecked:false,root:{},rootChecked:false,check:{},checkChecked:false};
const treeParts={
wurzeln:{name:'Wurzeln',image:'baum.png',alt:'Weit verzweigte Wurzeln unter einem Laubbaum',text:'Die Wurzeln verankern den Baum im Boden. Sie nehmen Wasser und darin gelöste Mineralstoffe auf. Außerdem können sie Nährstoffe speichern, zum Beispiel Stärke.',more:'Viele Verzweigungen erschließen einen großen Bodenraum. An jungen Wurzelabschnitten sitzen feine Wurzelhaare. Diese lernst du in der Wurzellupe kennen.'},
stamm:{name:'Stamm',image:'stamm.png',alt:'Baumstamm mit schützender Borke und sichtbarem innerem Holz',text:'Der Stamm ist die verholzte Sprossachse des Baumes. Er trägt die Krone und verbindet die Wurzeln mit den Ästen und Blättern. In seinem Inneren werden Wasser, Mineralstoffe und Zucker transportiert.',more:'Die äußere Borke bildet eine Schutzschicht. Sie schützt darunterliegendes Gewebe zum Beispiel vor Verletzungen und Austrocknung. Die Borke selbst ist keine Wasserleitung.'},
krone:{name:'Krone mit Laubblättern',image:'laubblatt.png',alt:'Grünes Laubblatt mit verzweigten Blattadern',text:'Zur Krone gehören Äste, Zweige und Blätter. Die Äste und Zweige tragen die Blätter und verteilen sie im Licht.',more:'In den Laubblättern findet Fotosynthese statt: Mit Licht entstehen aus Wasser und Kohlenstoffdioxid Zucker und Sauerstoff. Zucker dient der Pflanze als Energiequelle und Baustoff. Dafür musst du den inneren Blattaufbau noch nicht kennen.'}
};
function treeSteps(route){return '<nav class="steps" aria-label="Lernschritte zum Baum">'+treeOrder.map((s,i)=>'<a class="step" href="#'+s+'" '+(route===s?'aria-current="step"':'')+'>'+(i+1)+' · '+treeLabels[i]+'</a>').join('')+'</nav>';}
const treeZones=[{id:'krone',letter:'A',x:62,y:30},{id:'stamm',letter:'B',x:50,y:57},{id:'wurzeln',letter:'C',x:57,y:79}];
function assignTreePart(zone,term){if(!treeZones.some(z=>z.id===zone)||!treeParts[term])throw Error('Ungültige Zuordnung');for(const z of Object.keys(treeState.assigned))if(treeState.assigned[z]===term)delete treeState.assigned[z];treeState.assigned[zone]=term;treeState.exploreChecked=false;treeState.part=term;}
function treeFigure(markers=true){return '<div class="tree-figure"><img src="assets/baum.png" alt="Laubbaum mit drei zu beschriftenden Bereichen">'+(markers?treeZones.map(z=>{const v=treeState.assigned[z.id];return '<button class="tree-drop '+(v?'filled ':'')+(treeState.exploreChecked?(v===z.id?'correct':'wrong'):'')+'" style="left:'+z.x+'%;top:'+z.y+'%" data-tree-zone="'+z.id+'" aria-label="Bereich '+z.letter+(v?': '+treeParts[v].name:': Begriff ablegen')+'"><strong>'+z.letter+'</strong><span>'+(v?treeParts[v].name:'Hier ablegen')+'</span></button>';}).join(''):'')+'</div>';}
function treeExplore(){const part=treeParts[treeState.part];const score=treeZones.filter(z=>treeState.assigned[z.id]===z.id).length;
return heading('Thema 01 · Bau eines Baumes','Wurzel, Stamm und Krone','Ziehe die drei Begriffe auf die passenden Bereiche A, B und C. Klicke einen Begriff an, um seine Beschreibung zu lesen.')+
'<div class="tree-explore"><section>'+treeFigure()+'<p class="subtle">Du kannst auch einen Begriff auswählen und anschließend auf einen Ablagebereich klicken.</p><button class="button" data-tree-check="explore">Zuordnung prüfen</button>'+treeResult(treeState.exploreChecked,score,3)+'</section><section class="panel tree-detail"><h2>Deine Begriffe</h2><div class="tree-part-buttons">'+['stamm','wurzeln','krone'].map(id=>'<button class="term tree-drag" draggable="true" data-tree-term="'+id+'" aria-pressed="'+(treeState.part===id)+'">'+treeParts[id].name+'</button>').join('')+'</div><div aria-live="polite">'+(part?'<h3>'+part.name+'</h3><img class="'+(treeState.part==='wurzeln'?'root-close':'')+'" src="assets/'+part.image+'" alt="'+part.alt+'"><p>'+part.text+'</p><p>'+part.more+'</p>':'<p>Wähle einen Begriff. Seine Beschreibung hilft dir bei der Zuordnung und erklärt seine Aufgaben.</p>')+'</div><p class="subtle">Zum Ändern ziehst du einen Begriff an eine andere Stelle. Jeder Begriff wird nur einmal verwendet.</p></section></div>'+actions('zusatz','baum-bauplan');}
const planQs=[
{q:'Was gehört zum Spross eines Baumes?',choices:['Nur die Wurzeln','Stamm und Krone','Nur die Laubblätter'],answer:'1',why:'Der oberirdische Spross umfasst beim Baum Stamm und Krone.'},
{q:'Was gehört zur Krone?',choices:['Äste, Zweige und Blätter','Stamm und Wurzeln','Nur die Blätter'],answer:'0',why:'Die Blätter sitzen an Zweigen und Ästen. Zusammen bilden sie die Krone.'},
{q:'Wie heißt die Sprossachse bei einem Baum?',choices:['Wurzelhaar','Borke','Stamm'],answer:'2',why:'Der verholzte Stamm ist die Sprossachse des Baumes.'}];
function treeSelect(key,index,choices,value,checked,answer){return '<select data-tree-group="'+key+'" data-tree-index="'+index+'" aria-label="'+(key==='functions'?'Funktion ':key==='plan'?'Frage ':key==='root'?'Wurzelaufgabe ':'Aussage ')+(Number(index)+1)+'" class="'+(checked?(value===answer?'correct':'wrong'):'')+'"><option value="">Bitte wählen …</option>'+choices.map((c,i)=>'<option value="'+i+'" '+(value===String(i)?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select>';}
function treeResult(checked,score,total){return '<div class="feedback" role="status">'+(checked?(score===total?'<span class="ok">✓ Alles richtig!</span>':'<span class="bad">'+score+' von '+total+' richtig. Überarbeite die markierten Antworten.</span>'):'')+'</div>';}
function planPage(){return heading('02 · Der Grundbauplan','Ein Baum ist eine Pflanze','Wurzeln und Spross bilden den Grundbauplan. Beim Baum sind viele Teile groß und verholzt.')+
'<div class="tree-questions">'+planQs.map((q,i)=>'<section class="panel"><h2>'+q.q+'</h2>'+treeSelect('plan',i,q.choices,treeState.plan[i],treeState.planChecked,q.answer)+(treeState.planChecked?'<p class="answer-note">'+(treeState.plan[i]===q.answer?'✓ '+q.why:'Noch nicht richtig. Lies die Infotexte in der Erkundung noch einmal.')+'</p>':'')+'</section>').join('')+'</div><div class="actions"><button class="button" data-tree-check="plan">Grundbauplan prüfen</button>'+treeResult(treeState.planChecked,planQs.filter((q,i)=>treeState.plan[i]===q.answer).length,3)+'</div>'+actions('baum','baum-aufgaben');}
const functionCards=[
{text:'Verankern den Baum im Boden.',answer:'0',hint:'Gesucht ist der weit verzweigte Bereich unter der Erde.'},
{text:'Trägt die Krone.',answer:'1',hint:'Gesucht ist die stabile Verbindung zwischen Wurzeln und Krone.'},
{text:'Stellen bei der Fotosynthese Zucker her.',answer:'2',hint:'Diese grünen Teile nehmen Licht auf.'},
{text:'Nehmen Wasser und gelöste Mineralstoffe aus dem Boden auf.',answer:'0',hint:'Welcher Bereich hat direkten Kontakt zum Boden?'},
{text:'Transportiert Stoffe zwischen Wurzeln und Krone.',answer:'1',hint:'Die Leitungsbahnen verlaufen durch die Sprossachse.'},
{text:'Speichern Nährstoffe, zum Beispiel Stärke.',answer:'0',hint:'Auch der unterirdische Bereich kann als Vorratsspeicher dienen.'},
{text:'Nehmen Licht für die Fotosynthese auf.',answer:'2',hint:'Gesucht sind die flächigen grünen Teile in der Krone.'},
{text:'Wird außen durch die Borke geschützt.',answer:'1',hint:'Die Borke ist die äußere Schutzschicht der Sprossachse.'}];
function functionsPage(){const score=functionCards.filter((q,i)=>treeState.functions[i]===q.answer).length;
return heading('03 · Funktionen zuordnen','Wer übernimmt welche Aufgabe?','Ordne jede Aussage den Wurzeln, dem Stamm oder den Laubblättern zu. Ein Bereich kann mehrere Aufgaben haben.')+
'<div class="function-cards">'+functionCards.map((q,i)=>'<section class="panel"><label for="function-'+i+'"><span class="tag">'+(i+1)+'</span><strong>'+q.text+'</strong></label>'+treeSelect('functions',i,['Wurzeln','Stamm','Laubblätter'],treeState.functions[i],treeState.functionsChecked,q.answer).replace('<select ','<select id="function-'+i+'" ')+(treeState.functionsChecked?'<p class="answer-note">'+(treeState.functions[i]===q.answer?'✓ Richtig zugeordnet.':q.hint)+'</p>':'')+'</section>').join('')+'</div><div class="actions"><a class="button secondary" href="#baum">Infotexte nachlesen</a><button class="button" data-tree-check="functions">Zuordnung prüfen</button></div>'+treeResult(treeState.functionsChecked,score,8)+actions('baum-bauplan','baum-wurzel');}
const rootQs=[
{q:'Welche Struktur ist bei A markiert?',choices:['Wurzelhaube','Wurzelhaare'],answer:'1',hint:'Gesucht sind die feinen seitlichen Ausstülpungen.'},
{q:'Welche Struktur ist bei B markiert?',choices:['Wurzelhaube','Wurzelhaare'],answer:'0',hint:'Gesucht ist der Schutz an der empfindlichen Spitze.'},
{q:'Warum helfen viele Wurzelhaare bei der Wasseraufnahme?',choices:['Sie verlängern die Wurzel so stark, dass sie tiefere Bodenschichten erreicht.','Sie vergrößern die Fläche, über die Wasser aus dem Boden aufgenommen wird.','Sie speichern Wasser außerhalb der Wurzel und geben es erst bei Trockenheit ab.'],answer:'1',hint:'Denke an die zusätzliche Oberfläche.'}];
function rootChoices(q,i){if(i!==2)return treeSelect('root',i,q.choices,treeState.root[i],treeState.rootChecked,q.answer);return '<fieldset class="root-mc"><legend>Wähle genau eine Antwort.</legend>'+q.choices.map((c,k)=>'<label><input type="radio" name="root-water" data-tree-group="root" data-tree-index="2" value="'+k+'" '+(treeState.root[2]===String(k)?'checked':'')+'> <span>'+esc(c)+'</span></label>').join('')+'</fieldset>';}

function rootPage(){return heading('04 · Wurzellupe','Kleine Haare, große Aufnahmefläche','Wurzelhaare sind viel feiner als verzweigte Wurzeln. Die Zeichnung zeigt stark vergrößert einen jungen Wurzelabschnitt.')+
'<div class="lead-grid"><figure class="panel" style="margin:0"><div class="root-figure"><img class="micro-image" src="assets/wurzelspitze.png" alt="Junger Wurzelabschnitt mit feinen seitlichen Wurzelhaaren und einer glatten Spitze mit Wurzelhaube"><span class="root-mark" style="left:70%;top:35%" aria-label="Markierung A">A</span><span class="root-mark" style="left:50%;top:85%" aria-label="Markierung B">B</span></div><figcaption class="caption">Vereinfachte, KI-generierte Zeichnung; nicht maßstabsgetreu.</figcaption></figure><section><h2>Aufnehmen und schützen</h2><p><strong>Wurzelhaare</strong> sind dünne Ausstülpungen einzelner äußerer Wurzelzellen. Sie vergrößern die Oberfläche der Wurzel. Über diese Fläche nimmt die Pflanze Wasser und darin gelöste Mineralstoffe auf.</p><p>Die <strong>Wurzelhaube</strong> schützt die empfindliche Spitze, wenn die Wurzel durch den Boden wächst. Direkt an der Spitze sitzen keine Wurzelhaare.</p></section></div><div class="tree-questions">'+rootQs.map((q,i)=>'<section class="panel '+(i===2?'root-mc-card':'')+'"><h2>'+q.q+'</h2>'+rootChoices(q,i)+(treeState.rootChecked?'<p class="answer-note">'+(treeState.root[i]===q.answer?'✓ Richtig.':q.hint)+'</p>':'')+'</section>').join('')+'</div><button class="button" data-tree-check="root">Antworten prüfen</button>'+treeResult(treeState.rootChecked,rootQs.filter((q,i)=>treeState.root[i]===q.answer).length,3)+actions('baum-aufgaben','baum-check');}
const checkQs=[
{text:'Die Wurzeln halten den Baum im Boden.',answer:'0',why:'Richtig: Die verzweigten Wurzeln verankern den Baum.'},
{text:'Die Borke nimmt Wasser aus dem Boden auf.',answer:'1',why:'Die Wurzeln nehmen Wasser auf. Die Borke schützt den Stamm.'},
{text:'Der Stamm trägt die Krone und transportiert Stoffe.',answer:'0',why:'Richtig: Der Stamm gibt Halt und enthält Leitungsbahnen.'},
{text:'Zur Krone gehören nur die Blätter.',answer:'1',why:'Zur Krone gehören Äste, Zweige und Blätter.'},
{text:'Die Wurzelhaube schützt die empfindliche Wurzelspitze.',answer:'0',why:'Richtig: Die Wurzelhaube schützt die Spitze beim Wachstum durch den Boden.'}];
const originalCheckOrder=checkQs.slice();checkQs.splice(0,checkQs.length,...[3,0,4,1,2].map(i=>originalCheckOrder[i]));
function checkPage(){return heading('05 · Wissenscheck','Stimmt das wirklich?','Entscheide bei jeder Aussage: richtig oder falsch? Prüfe deine Antworten und berichtige die falschen Aussagen auf dem Arbeitsblatt.')+
'<div class="tree-check">'+checkQs.map((q,i)=>'<section class="panel"><h2>'+(i+1)+'. '+q.text+'</h2>'+treeSelect('check',i,['Richtig','Falsch'],treeState.check[i],treeState.checkChecked,q.answer)+(treeState.checkChecked?'<p class="answer-note">'+(treeState.check[i]===q.answer?'✓ ':'✕ ')+q.why+'</p>':'')+'</section>').join('')+'</div><button class="button" data-tree-check="check">Wissenscheck prüfen</button>'+treeResult(treeState.checkChecked,checkQs.filter((q,i)=>treeState.check[i]===q.answer).length,5)+actions('baum-wurzel','baum-abschluss');}
function treeClosing(){return heading('06 · Abschluss','Ein Baum funktioniert im Zusammenspiel','Du hast den Grundbauplan eines Baumes kennengelernt und seine wichtigsten Aufgaben zugeordnet.')+
'<div class="lead-grid">'+treeFigure(false)+'<section class="panel"><h2>Das gehört zusammen</h2><p><strong>Wurzeln</strong> verankern den Baum, nehmen Wasser und Mineralstoffe auf und speichern Nährstoffe.</p><p><strong>Der Stamm</strong> trägt die Krone und transportiert Stoffe. Seine Borke schützt ihn.</p><p><strong>Die Krone</strong> trägt die Laubblätter. In den Blättern entsteht bei der Fotosynthese Zucker.</p><p><strong>Wurzelhaare</strong> vergrößern die Aufnahmefläche. Die <strong>Wurzelhaube</strong> schützt die Spitze.</p></section></div><section class="completion"><h2>Jeder Teil erfüllt eine Aufgabe</h2><p>Zusammen ermöglichen die Teile des Baumes, dass er versorgt und geschützt wird und wachsen kann. Sein Bau passt zu diesen Aufgaben – von den feinen Wurzelhaaren bis zur großen Krone.</p></section>'+actions('baum-check','zusatz','Zu den Zusatzaufgaben');}
const treePages={baum:treeExplore,'baum-bauplan':planPage,'baum-aufgaben':functionsPage,'baum-wurzel':rootPage,'baum-check':checkPage,'baum-abschluss':treeClosing};
function setTreeAnswer(group,index,value){const groups={plan:planQs,functions:functionCards,root:rootQs,check:checkQs};if(!groups[group]||!Number.isInteger(index)||index<0||index>=groups[group].length)throw Error('Ungültige Aufgabe');const count=groups[group][index].choices?.length||(group==='check'?2:3);if(value!==''&&(!/^\d+$/.test(value)||Number(value)>=count))throw Error('Ungültige Auswahl');treeState[group][index]=value;treeState[group+'Checked']=false;}
function installTreeEvents(){
let touchDrag=null;let suppressClick=false;
function place(zone,term){assignTreePart(zone,term);render();root.querySelector('[data-tree-zone="'+zone+'"]')?.focus();}
root.addEventListener('dragstart',e=>{const b=e.target.closest('[data-tree-term]');if(!b)return;e.dataTransfer.setData('text/plain',b.dataset.treeTerm);e.dataTransfer.effectAllowed='move';});
root.addEventListener('dragover',e=>{if(e.target.closest('[data-tree-zone]')){e.preventDefault();e.dataTransfer.dropEffect='move';}});
root.addEventListener('drop',e=>{const z=e.target.closest('[data-tree-zone]');if(!z)return;e.preventDefault();const term=e.dataTransfer.getData('text/plain');if(treeParts[term])place(z.dataset.treeZone,term);});
root.addEventListener('pointerdown',e=>{const b=e.target.closest('[data-tree-term]');if(!b||e.pointerType==='mouse')return;touchDrag={id:e.pointerId,term:b.dataset.treeTerm,x:e.clientX,y:e.clientY,moved:false,button:b};b.setPointerCapture(e.pointerId);});
root.addEventListener('pointermove',e=>{if(!touchDrag||touchDrag.id!==e.pointerId)return;if(Math.hypot(e.clientX-touchDrag.x,e.clientY-touchDrag.y)>7)touchDrag.moved=true;if(touchDrag.moved){touchDrag.button.classList.add('dragging');root.querySelectorAll('[data-tree-zone]').forEach(z=>z.classList.remove('drop-hover'));document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tree-zone]')?.classList.add('drop-hover');}});
root.addEventListener('pointerup',e=>{if(!touchDrag||touchDrag.id!==e.pointerId)return;const d=touchDrag;touchDrag=null;d.button.classList.remove('dragging');root.querySelectorAll('[data-tree-zone]').forEach(z=>z.classList.remove('drop-hover'));if(d.moved){suppressClick=true;setTimeout(()=>{suppressClick=false},0);const z=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-tree-zone]');if(z)place(z.dataset.treeZone,d.term);}});
root.addEventListener('pointercancel',()=>{if(touchDrag)touchDrag.button.classList.remove('dragging');touchDrag=null;root.querySelectorAll('[data-tree-zone]').forEach(z=>z.classList.remove('drop-hover'));});
root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||suppressClick)return;if(b.dataset.treeTerm){treeState.part=b.dataset.treeTerm;render();root.querySelector('[data-tree-term="'+treeState.part+'"]')?.focus();}if(b.dataset.treeZone&&treeState.part)place(b.dataset.treeZone,treeState.part);if(b.dataset.treeCheck){const group=b.dataset.treeCheck;if(!['explore','plan','functions','root','check'].includes(group))return;treeState[group+'Checked']=true;render();root.querySelector('[data-tree-check="'+group+'"]')?.focus();}});
root.addEventListener('change',e=>{const el=e.target;if(el.dataset.treeGroup){setTreeAnswer(el.dataset.treeGroup,Number(el.dataset.treeIndex),el.value);render();root.querySelector('[data-tree-group="'+el.dataset.treeGroup+'"][data-tree-index="'+el.dataset.treeIndex+'"]'+(el.type==='radio'?'[value="'+el.value+'"]':''))?.focus();}});}
